### ISSUE TITLE
No configuration setting found for key 'akka.version'

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-landuse#1]
When I try:

``` sh
java -cp target/biggis-landuse-0.0.1-SNAPSHOT.jar \
  biggis.landuse.spark.examples.GeotiffToPyramid \
  ./data/DOP_RGBI_T2.tif \
  new_layer \
  ./data/pyramid
```

I get the following error message: 

```
09:25:35 INFO  org.apache.spark.util.Utils                                   - Successfully started service 'sparkDriver' on port 54655.
09:25:35 ERROR org.apache.spark.SparkContext                                 - Error initializing SparkContext.
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
        at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
        at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
        at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:2024)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:2015)
        at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
        at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
        at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
        at biggis.landuse.spark.examples.GeotiffToPyramid$.apply(GeotiffToPyramid.scala:55)
        at biggis.landuse.spark.examples.GeotiffToPyramid$.main(GeotiffToPyramid.scala:41)
        at biggis.landuse.spark.examples.GeotiffToPyramid.main(GeotiffToPyramid.scala)
```

**Comment by vsimko** [comment]
Related stackoverflow entry:
http://stackoverflow.com/questions/31011243/no-configuration-setting-found-for-key-akka-version
