### ISSUE TITLE
MultibandGeotiffTilingExample invalid hdfs path

### ISSUE THREAD

**Issue by aklink** [biggis-project/biggis-landuse#16]
MultibandGeotiffTilingExample uses a wrong hdfs path, when running in a docker container that was not started in cluster mode (started via docker-compose)

when importing  
- **hdfs://**/landuse-demo/landuse/dop ("**hdfs://**"  + "/landuse-demo/landuse/dop")

then the path is falsely truncated to
- **hdfs:**/landuse-demo/landuse/dop  ("**hdfs:**"  + "/landuse-demo/landuse/dop")

similar behaviour to already closed issue https://github.com/biggis-project/biggis-landuse/issues/15,
in which a serialization of the hadoop config was necessary.

    implicit val conf: Configuration = sc.hadoopConfiguration
    val serConf = new SerializableConfiguration(conf)

unfortunatelly MultibandGeotiffTilingExample uses SparkContext for hadoopMultibandGeoTiffRDD directly, not the (to be serialized) hadoopConfiguration

    sc.hadoopMultibandGeoTiffRDD

**Comment by aklink** [comment]
18/05/30 15:35:59 INFO DeleteLayer$: Deleting layer layer_sat_4_10m including all zoom levels in catalog hdfs:///landuse-demo/geotrellis-catalog/ ...
18/05/30 15:35:59 INFO DeleteLayer$: done
18/05/30 15:35:59 INFO MultibandGeotiffTilingExample$: Loading geotiff 'hdfs:///landuse-demo/landuse//label_31467' into 'layer_label' in catalog 'hdfs:///landuse-demo/geotrellis-catalog/' ... 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.RuntimeException: hdfs:/landuse-demo/landuse/label_31467/*{.tif,.TIF,.tiff,.TIFF} contains no files.
	at scala.sys.package$.error(package.scala:27)
	at geotrellis.spark.io.hadoop.package$withHadoopConfigurationMethods.withInputDirectory(package.scala:46)
	at geotrellis.spark.io.hadoop.package$withHadoopConfigurationMethods.withInputDirectory(package.scala:61)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$.configuration(HadoopGeoTiffRDD.scala:87)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$.apply(HadoopGeoTiffRDD.scala:114)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$.apply(HadoopGeoTiffRDD.scala:153)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$.multiband(HadoopGeoTiffRDD.scala:223)
	at geotrellis.spark.io.hadoop.HadoopGeoTiffRDD$.spatialMultiband(HadoopGeoTiffRDD.scala:272)
	at geotrellis.spark.io.hadoop.HadoopSparkContextMethods$class.hadoopMultibandGeoTiffRDD(HadoopSparkContextMethods.scala:98)
	at geotrellis.spark.io.hadoop.Implicits$HadoopSparkContextMethodsWrapper.hadoopMultibandGeoTiffRDD(Implicits.scala:32)
	at geotrellis.spark.io.hadoop.HadoopSparkContextMethods$class.hadoopMultibandGeoTiffRDD(HadoopSparkContextMethods.scala:85)
	at geotrellis.spark.io.hadoop.Implicits$HadoopSparkContextMethodsWrapper.hadoopMultibandGeoTiffRDD(Implicits.scala:32)
	at biggis.landuse.spark.examples.MultibandGeotiffTilingExample$.apply(MultibandGeotiffTilingExample.scala:59)
	at biggis.landuse.spark.examples.ClusterTest$.apply(ClusterTest.scala:89)
	at biggis.landuse.spark.examples.ClusterTest$.main(ClusterTest.scala:19)
	at biggis.landuse.spark.examples.ClusterTest.main(ClusterTest.scala)
	... 6 more
18/05/30 15:35:59 INFO SparkContext: Invoking stop() from shutdown hook
18/05/30 15:35:59 INFO AbstractConnector: Stopped Spark@72b16078{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
18/05/30 15:35:59 INFO SparkUI: Stopped Spark web UI at http://172.20.0.7:4040
18/05/30 15:36:00 INFO StandaloneSchedulerBackend: Shutting down all executors
18/05/30 15:36:00 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
18/05/30 15:36:00 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
18/05/30 15:36:00 INFO MemoryStore: MemoryStore cleared
18/05/30 15:36:00 INFO BlockManager: BlockManager stopped

**Comment by aklink** [comment]
was fixed long time ago (using hadoop serialized conf)
