### ISSUE TITLE
Hadoop Layer Writer - Directory already exists

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-landuse#9]
The following code was working fine with Geotrellis 0.10.3 and Spark 1.6.2:
 
```scala
// Create the writer that we will use to store the tiles in the local catalog.
val writer = HadoopLayerWriter(catalogPathHdfs, attributeStore)
val layerId = LayerId(layerName, zoom)
[..]
logger debug "Writing reprojected tiles using space filling curve"
writer.write(layerId, reprojected, ZCurveKeyIndexMethod)
```
Using Geotrellis 1.0.0 and Spark 2.1.0 now I get the failure:
 
```
10:29:29 INFO  org.apache.spark.storage.BlockManagerInfo                     - Removed broadcast_7_piece0 on 10.0.75.1:53190 in memory (size: 6.9 KB, free: 4.1 GB)
Exception in thread "main" geotrellis.spark.io.package$LayerWriteError: Failed to write Layer(name = "layer_label", zoom = 17)
                at geotrellis.spark.io.hadoop.HadoopLayerWriter._write(HadoopLayerWriter.scala:63)
                at geotrellis.spark.io.hadoop.HadoopLayerWriter._write(HadoopLayerWriter.scala:36)
                at geotrellis.spark.io.LayerWriter$class.write(LayerWriter.scala:59)
                at geotrellis.spark.io.hadoop.HadoopLayerWriter.write(HadoopLayerWriter.scala:36)
                at biggis.landuse.spark.examples.MultibandGeotiffTilingExample$.apply(MultibandGeotiffTilingExample.scala:76)
                at biggis.landuse.spark.examples.WorkflowExample$.apply(WorkflowExample.scala:52)
                at biggis.landuse.spark.examples.WorkflowExample$.main(WorkflowExample.scala:15)
                at biggis.landuse.spark.examples.WorkflowExample.main(WorkflowExample.scala)
Caused by: java.lang.Exception: Directory already exists: target/geotrellis-catalog/layer_label/17
                at geotrellis.spark.io.hadoop.HadoopRDDWriter$.write(HadoopRDDWriter.scala:85)
                at geotrellis.spark.io.hadoop.HadoopLayerWriter._write(HadoopLayerWriter.scala:65)
                ... 7 more
 ```
The write fails after creating the layer (zoom level 17 and partitions inside exist, also meta data for layer exists). I have cleaned the geotrellis-catalog before (to avoid data conflict between versions).

**Comment by aklink** [comment]
After further testing, it isn't problem of write process. The write process finished successfully, but reading afterwards fails. Also deleting fails, because **attributeStore.layerExists(layerId)** check fails. This is causing **Directory already exists** issue upon re-writing the layer in workflow. 

layerExists check fails, therefore deleting fails:
```
    if (attributeStore.layerExists(layerId)) {
      logger debug s"Layer $layerIdOut already exists, deleting ..."
      HadoopLayerDeleter(attributeStore).delete(layerId)
    }
```

Reading Layer fails:
```
    // Create the attributes store that will tell us information about our catalog.
    val catalogPathHdfs = new Path(catalogPath)
    implicit val attributeStore = HadoopAttributeStore(catalogPathHdfs)
    val layerReader = HadoopLayerReader(attributeStore)

    val tiles: RDD[(SpatialKey, MultibandTile)] with Metadata[TileLayerMetadata[SpatialKey]] =
      layerReader.read[SpatialKey, MultibandTile, TileLayerMetadata[SpatialKey]](layerId)
```

```
13:30:03 INFO  biggis.landuse.spark.examples.ManyLayersToMultibandLayer$     - Combining 'layer_label' and 'layer_sat' into layer_label_sat inside 'target/geotrellis-catalog'
Layer(name = "layer_label", zoom = 17), Layer(name = "layer_sat", zoom = 17)
Exception in thread "main" geotrellis.spark.io.package$LayerNotFoundError: Layer Layer(name = "layer_label", zoom = 17) not found in the catalog
	at geotrellis.spark.io.hadoop.HadoopLayerReader.read(HadoopLayerReader.scala:57)
	at geotrellis.spark.io.hadoop.HadoopLayerReader.read(HadoopLayerReader.scala:45)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:57)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:71)
	at geotrellis.spark.io.LayerReader$class.read(LayerReader.scala:48)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:29)
	at biggis.landuse.spark.examples.ManyLayersToMultibandLayer$.apply(ManyLayersToMultibandLayer.scala:54)
	at biggis.landuse.spark.examples.WorkflowExample$.apply(WorkflowExample.scala:61)
	at biggis.landuse.spark.examples.WorkflowExample$.main(WorkflowExample.scala:15)
	at biggis.landuse.spark.examples.WorkflowExample.main(WorkflowExample.scala)
```

**Comment by aklink** [comment]
Same behaviour in **GettingStarted** Example in **NDVILayerWithCloudMaskExample**:

```
val tilesNIR: RDD[(SpatialKey, Tile)] with Metadata[TileLayerMetadata[SpatialKey]] =
      layerReader.read[SpatialKey, Tile, TileLayerMetadata[SpatialKey]](layerIdNIR)
```
fails reading an existing layer previously written in GeotiffTilingExample using the HadoopLayerWriter, showing the following error message:
```
13:46:40 INFO  biggis.landuse.spark.examples.NDVILayerWithCloudMaskExample$  - Running ndvi calc of layers 'layer_L8_B5_nir' - 'layer_L8_B4_red' in catalog 'target/geotrellis-catalog'
Layer(name = "layer_L8_B5_nir", zoom = 13), Layer(name = "layer_L8_B4_red", zoom = 13)
Exception in thread "main" geotrellis.spark.io.package$LayerNotFoundError: Layer Layer(name = "layer_L8_B5_nir", zoom = 13) not found in the catalog
	at geotrellis.spark.io.hadoop.HadoopLayerReader.read(HadoopLayerReader.scala:57)
	at geotrellis.spark.io.hadoop.HadoopLayerReader.read(HadoopLayerReader.scala:45)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:57)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:71)
	at geotrellis.spark.io.LayerReader$class.read(LayerReader.scala:48)
	at geotrellis.spark.io.FilteringLayerReader.read(FilteringLayerReader.scala:29)
	at biggis.landuse.spark.examples.NDVILayerWithCloudMaskExample$.apply(NDVILayerWithCloudMaskExample.scala:46)
	at biggis.landuse.spark.examples.GettingStarted$.apply(GettingStarted.scala:63)
	at biggis.landuse.spark.examples.GettingStarted$.main(GettingStarted.scala:20)
	at biggis.landuse.spark.examples.GettingStarted.main(GettingStarted.scala)
```

The HDFS is set to local filesystem using VM option **-Dspark.master=local[*]**

**Comment by aklink** [comment]
Found issue that might be related:
**ETL: Layer exists returns false for layerIds(0) #2113** https://github.com/locationtech/geotrellis/issues/2113

it seems similar to failing
```
if (attributeStore.layerExists(layerId)) {
      logger debug s"Layer $layerIdOut already exists, deleting ..."
      HadoopLayerDeleter(attributeStore).delete(layerId)
    }
```
but I am not sure if this is also the same reason for failing **layerReader.read**

**Comment by aklink** [comment]
for failing code examples (using the https://github.com/geotrellis/geotrellis-landsat-tutorial example image data) see: 
- https://github.com/biggis-project/biggis-landuse/blob/feature/spark_2.1.0/src/main/scala/biggis/landuse/spark/examples/GettingStarted.scala
- https://github.com/biggis-project/biggis-landuse/blob/feature/spark_2.1.0/src/main/scala/biggis/landuse/spark/examples/NDVILayerWithCloudMaskExample.scala

**Comment by aklink** [comment]
also see:
**Get absolute path for attributePath #2123** https://github.com/locationtech/geotrellis/pull/2123
May this be a possible bugfix?

**Comment by aklink** [comment]
**Geotrellis 1.1.0-RC3** solves this bug.

**In HadoopAttributeStore, get absolute path for attributePath #2123** https://github.com/locationtech/geotrellis/pull/2123
